---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/snowsql --version
      register: snowsql_test_output
    - name: snowsql --version
      debug:
        msg: '{{ snowsql_test_output.stdout }}'
